// this file was auto generated by D:\nightly_build\VizArtist-3.11.1\Common\Bin\make_version.cmd @ 2018-08-28
// PROJECTNAME=Viz 
// CD=D:\nightly_build\VizArtist-3.11.1\Viz
// SVNREVDIR=D:\nightly_build\VizArtist-3.11.1\Viz\ 
// 
#pragma once
#if ! defined( VIZARTIST_VERSION_H )
#define VIZARTIST_VERSION_H

// product version as major, minor, patch, working copy revision number
constexpr int VIZARTIST_PROD_VERS_MAJOR = 3;
constexpr int VIZARTIST_PROD_VERS_MINOR = 11;
constexpr int VIZARTIST_PROD_VERS_PATCH = 1;

// PROD_PREREL is set to zero if it is a stable build used for distributions
// trunk version usually have it set to something other than zero
constexpr int VIZARTIST_PROD_PREREL = 0;

// PROD_PRIV_BUILD is set to zero if it is an official build done by the build server
// developer builds usually have it set to something other than zero
constexpr int VIZARTIST_PROD_PRIV_BUILD = 1;

// file version as major, minor, patch, working copy revision number
constexpr int  VIZARTIST_FILE_VERS_MAJOR = 3;
constexpr int  VIZARTIST_FILE_VERS_MINOR = 11;
constexpr int  VIZARTIST_FILE_VERS_PATCH = 1;

// do not use WCREV_NUM, WCREV_STR or WCRANGE_STR anywhere since it most likely differs from svnversion. see also JIRA VIZENG-5641
// WCREV_NUM: working copy revision as a number. please see ""C:\Program Files\TortoiseSVN\bin\SubWCRev.exe" D:\nightly_build\VizArtist-3.11.1\Viz\"

// WCDATE: working copy last revision date as a string. please see ""C:\Program Files\TortoiseSVN\bin\SubWCRev.exe" D:\nightly_build\VizArtist-3.11.1\Viz\"
constexpr char const VIZARTIST_WCDATE[] = "2018-08-24T14:56:54";


// VIZARTIST_I_HEADREV_NUM is only the first revision in case of a revision range.
// if VIZARTIST_I_HEADREV_NUM is not a single number then you have most likely a range of revisions.
// please update with the CM scripts or update in the top most directory.
constexpr int  VIZARTIST_I_HEADREV_NUM = 78977;
constexpr int  VIZARTIST_W_HEADREV_NUM = 8977;

// HEADREV_STR: repository head revision as a string. please see ""C:\Program Files\TortoiseSVN\bin\svnversion.exe" D:\nightly_build\VizArtist-3.11.1\Viz\"
constexpr char const VIZARTIST_HEADREV_STR[] = "78977";
// I_PROD_VERS: product version as major, minor, patch, first working copy revision number
// I_FILE VERS: file version as major minor patch. first working copy revision number
// W_PROD_VERS: product version as major, minor, patch, first working copy revision number modulo, for windows version struct
// W_FILE VERS: file version as major minor patch. first working copy revision number modulo, for windows version struct
// #define VIZARTIST_I_PROD_VERS        VIZARTIST_PROD_VERS_MAJOR,VIZARTIST_PROD_VERS_MINOR,VIZARTIST_PROD_VERS_PATCH,VIZARTIST_I_HEADREV_NUM
// #define VIZARTIST_I_FILE_VERS        VIZARTIST_FILE_VERS_MAJOR,VIZARTIST_FILE_VERS_MINOR,VIZARTIST_FILE_VERS_PATCH,VIZARTIST_I_HEADREV_NUM
// #define VIZARTIST_W_PROD_VERS        VIZARTIST_PROD_VERS_MAJOR,VIZARTIST_PROD_VERS_MINOR,VIZARTIST_PROD_VERS_PATCH,VIZARTIST_W_HEADREV_NUM
// #define VIZARTIST_W_FILE_VERS        VIZARTIST_FILE_VERS_MAJOR,VIZARTIST_FILE_VERS_MINOR,VIZARTIST_FILE_VERS_PATCH,VIZARTIST_W_HEADREV_NUM

// PROD_VERS: product version as major, minor, patch, first working copy revision number
// FILE VERS: file version as major minor patch. first working copy revision number
// MMP_VERS:  product version as major minor patch. no revision number. to populate the windows app data paths
constexpr char const VIZARTIST_PROD_VERS_STR[] = "3.11.1.78977";
constexpr char const VIZARTIST_FILE_VERS_STR[] = "3.11.1.78977";
constexpr char const VIZARTIST_MMP_VERS_STR[]  = "3.11.1";

constexpr char const VIZARTIST_COPYRIGHT[] = "Copyright (c) 1999-2018 vizrt";

#endif // #if ! defined( VIZARTIST_VERSION_H )

